version: '3.8'
# Docker atualizado -> zabbix agent 2, pmm 3 (server e client)
services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db
    restart: always
    command: postgres -c shared_preload_libraries=pg_stat_statements -c track_activity_query_size=2048 -c pg_stat_statements.track=all -c track_io_timing=on
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
    volumes:
      - ./dados_banco:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - monitoramento-net

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_ui
    restart: always
    user: "5050:5050"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin_password
    volumes:
      - ./dados_pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - monitoramento-net

  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-6.4-latest
    container_name: zabbix_server
    restart: always
    environment:
      ZBX_DBTYPE: postgresql
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
    ports:
      - "10051:10051"
    volumes:
      - ./dados_zabbix_export:/var/lib/zabbix/export
    depends_on:
      - postgres
    networks:
      - monitoramento-net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-6.4-latest
    container_name: zabbix_web
    restart: always
    environment:
      ZBX_DBTYPE: postgresql
      ZBX_SERVER_HOST: zabbix-server
      DB_SERVER_HOST: postgres
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix_password
      POSTGRES_DB: zabbix
    ports:
      - "8081:8080"
    depends_on:
      - postgres
      - zabbix-server
    networks:
      - monitoramento-net

  zabbix-agent:
    image: zabbix/zabbix-agent2:ubuntu-6.4-latest
    container_name: zabbix_agent
    restart: always
    privileged: true
    pid: "host"
    ports:
      - "10050:10050"
    environment:
      ZBX_HOSTNAME: "Zabbix server"
      ZBX_SERVER_HOST: "zabbix-server"
    volumes:
      - /:/host:ro
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
    networks:
      - monitoramento-net

  pmm-server:
    image: percona/pmm-server:3
    container_name: pmm-server
    restart: always
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./dados_pmm:/srv
    networks:
      - monitoramento-net
    labels:
      - "com.centurylinklabs.watchtower.enable=true"

  watchtower:
    image: containrrr/watchtower
    container_name: pmm-watchtower
    restart: always
    command: --label-enable --interval 86400
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    networks:
      - monitoramento-net
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_INCLUDE_STOPPED=false

  pmm-client:
    image: percona/pmm-client:3
    container_name: pmm-client
    restart: always
    environment:
      - PMM_AGENT_SERVER_ADDRESS=pmm-server:443
      - PMM_AGENT_SERVER_USERNAME=admin
      - PMM_AGENT_SERVER_PASSWORD=admin
      # Desativa a verificação TSL do PMM!!!!
      - PMM_AGENT_SERVER_INSECURE_TLS=1
    networks:
      - monitoramento-net
    depends_on:
      - pmm-server

  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana_ui
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./dados_grafana:/var/lib/grafana
    depends_on:
      - postgres
      - zabbix-server
      - pmm-server
    networks:
      - monitoramento-net

networks:
  monitoramento-net:
    driver: bridge
